### ISSUE TITLE
Please remove or hide this repository

### ISSUE THREAD

**Issue by erikvanoosten** [mlyu2010/golang#1]
Hello,

I noticed that this repository publishes an Ebay copyrighted assignment. Could you please remove or hide this repository?

Kind regards,
    Erik.

**Comment by mlyu2010** [comment]
Hello,

What exactly do you mean by "Ebay copyrighted assignment" ?

Regads.
Michael.

**Comment by erikvanoosten** [comment]
This file https://github.com/mlyu2010/golang/blob/master/csvprndata1/Workbook2.prn comes directly from an exercise designed here at eBay.

**Comment by mlyu2010** [comment]
The file deleted.

**Comment by erikvanoosten** [comment]
Sorry to be so annoying. The other file: Workbook.csv is also from the same assignment. Could you please delete that also?

**Comment by mlyu2010** [comment]
Done.

**Comment by erikvanoosten** [comment]
Thank you!

**Comment by talk2jaydip** [comment]
Deleted
